config/routes.rb
Rails.application.routes.draw do

  get 'tag/:id/posts' => 'tags#posts', :as => :tag_posts

  resources :post do 
    resources :tags
  get 'post/index'

  get 'post/show'

  get 'post/:id/tags' => 'post#tags', :as => :post_tags

  end

  resources :author
  root 'author#index'

  get 'author/:id' => 'author#show'

  get 'author/:id/posts' => 'author#posts', :as => :author_posts

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :posts
	has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :author
	has_and_belongs_to_many :tags
	has_many :comments
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
	def index
		@authors = Author.paginate(:page => params[:page], :per_page => 10)
	end
	def show
    	@author = Author.find(params[:id])
  	end
  	def posts
    	@author = Author.find(params[:id])
    	@posts = @author.posts.order('created_at DESC')
 	 end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
   def index
  	@posts = Post.paginate(:page => params[:page], :per_page => 10).order("created_at DESC")
  end

  def show
    @post = Post.find(find_params)
    @tags = @post.tags
  end
  private
    def find_params
      @post = Post.find(params[:id]) 
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def posts
    	@tag = Tag.find(params[:id])
    	@posts = @tag.posts.order('id DESC')
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/author/index.html.erb
 <%= will_paginate @authors %>
<h1>Авторы</h1>
<table class="table table-bordered">
	<tr>
	  <td>Id</td>
	  <td>Name</td>
	   <td>Email</td>
	   <td></td>
	</tr>
	<% @authors.each do |author| %>
	    <tr>
	      <td><%= author.id %></td>
	      <td><%= author.name %></td>
	      <td><%= author.email %></td>
	       <td><%= link_to "Подробнее", author_path(author.id)%> </td>
	    </tr>
	<% end %>
</table>
<br>
<table>
	<tr>
	</tr>
</table>
<a href="http://localhost:3000/">Список авторов</a>
<br>
<a href="http://localhost:3000/post">Список статей</a>

app/views/author/posts.html.erb
<h1>Список статей</h1>
<table class="table table-bordered">
<tr>
  <td>Id</td>
  <td>Title</td>
   <td>Author</td>
   <td>Date</td>
   <td></td>
</tr>
<% @posts.each do |post| %>
    <tr>
      <td><%= post.id %></td>
      <td><%= post.label %></td>
      <td><%= post.author.name %></td>
      <td><%= l post.created_at, format: :short%></td>
      <td><%= link_to "Просмотр", post_path(post.id) %></td>
      <td></td>
    </tr>
<% end %>
</table>
<a href="http://localhost:3000/">Список авторов</a>
<br>
<a href="http://localhost:3000/post">Список статей</a>

app/views/author/show.html.erb
<h2>Информация об авторе</h2>
<ul class="list-group" class="table table-bordered">
<li class="list-group-item">Id: <%= @author.id %></li>
<li class="list-group-item">Name: <%= @author.name %></li>
<li class="list-group-item">Email: <%= @author.email %></li>
<li class="list-group-item">City: <%= @author.city %></li>
<li class="list-group-item">Address: <%= @author.adress %></li>
<li class="list-group-item">Date born: <%= @author.birth %></li>
<li class="list-group-item"> <%= link_to "Список статей", author_posts_path(@author.id) %></li>
</ul>
</ul>
<a href="http://localhost:3000/">Список авторов</a>
<br>
<a href="http://localhost:3000/post">Список статей</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskRemote</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/post/index.html.erb
<h1>Список статей</h1>
<%= will_paginate @posts %>
<table class="table table-bordered">
<tr>
  <td>ID</td>
  <td>Title</td>
   <td>Text</td>
   <td>Author</td>
   <td>Tags</td>
   <td>Date create</td>
</tr>
<% @posts.each do |post| %>
    <tr>
      <td><%= post.id %></td>
      <td><%= post.label %></td>
      <td><%= post.text %></td>
      <td><%= post.author.name %></td>
      <td>
      <% post.tags.each do |tag| %>
              <%=link_to tag.name, tag_posts_path(tag.id)%>
      <%end%>
      </td>
      <td><%= l post.created_at, format: :short%></td>
      <td><%= link_to "Просмотреть", post_path(post.id) %></td>
    </tr>
<% end %>
</table>
<a href="http://localhost:3000/">Список авторов</a>
<br>
<a href="http://localhost:3000/post">Список статей</a>

app/views/post/show.html.erb
<h1>Статья</h1>
<ul class="list-group" class="table table-bordered">
<li class="list-group-item">Id: <%= @post.id %></li>
<li class="list-group-item">Title: <%= @post.label %></li>
<li class="list-group-item">Text: <%= @post.text %></li>
<li class="list-group-item"> 
    <% @tags.each do |tag| %>
            <%=link_to tag.name, tag_posts_path(tag.id)%>
    <%end%>
</li>
</ul>
<a href="http://localhost:3000/">Список авторов</a>
<br>
<a href="http://localhost:3000/post">Список статей</a>

app/views/tags/posts.html.erb
<h1>Список статей</h1>
<table class="table table-bordered">
<tr>
  <td>Id</td>
  <td>Title</td>
   <td>Author</td>
   <td>Tags</td>
   <td></td>
</tr>
<% @posts.each do |post| %>
    <tr>
      <td><%= post.id %></td>
      <td><%= post.label %></td>
      <td><%= post.author.name %></td>
      <td>
        <% post.tags.each do |tag| %>
                <%=link_to tag.name, tag_posts_path(tag.id)%>
        <%end%>
      </td>
      <td><%= link_to "Просмотреть", post_path(post.id) %></td>
    </tr>
<% end %>
</table>
<a href="http://localhost:3000/">Список авторов</a>
<br>
<a href="http://localhost:3000/post">Список статей</a>

app/views/tags/show.html.erb
<h1>Tag#show</h1>
<p>Find me in app/views/tag/show.html.erb</p>
<a href="http://localhost:3000/">Список авторов</a>
<br>
<a href="http://localhost:3000/post">Список статей</a>